name: orekit-factory
channels:
  - conda-forge
dependencies:
  - orekit=11.2
  - pip
  - python=3.10.4
  - requests
  - astropy
  # dev dependencies
  - pytest
  - pytest-cov
  - black
  - flake8
  - pip:
    # dev dependencies
    - build
    - pep517
